version: '3.8'

services:
  go-app:
    restart: always
    build: ./go-backend
    command: ./go-app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DB_PASSWORD: postgres
    networks:
      - app-network

  react:
    build: ./react-frontend
    ports:
      - "3000:3000"

  postgres:
    restart: always
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
