version: '3.8'

services:
  go-app:
    build: ./go-backend
    command: ./go-app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DB_PASSWORD: postgres

  react:
    build: ./react-frontend
    ports:
      - "3000:3000"

  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5436:5432
    networks:
      - app_network

networks:
  app_network:
    driver: bridge