port: ":8000"

db:
  username: "postgres"
  host: "postgres"
  port: "5432"
  dbname: "postgres"

health:
  health_check_interval: 40 # Интервал времени между проверками состояния агентов для Health checker
  max_inactive_time: 120 # Максимально допустимое время неактивности агента чтобы он перешел в статус missing
  very_max_inactive_time: 200 # Максимально допустимое время неактивности агента чтобы он перешел в статус dead

agent:
  get_task_time: 10 # Интервал времени между запросами задач агентами
  goroutines: 5 # Максимальное количество горутин на одного агента
